//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.ServiceClients.Products.ProductsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ProductsOverviewList", Namespace="http://schemas.datacontract.org/2004/07/Common.Dtos", ItemName="ProductsOverviewObject")]
    [System.SerializableAttribute()]
    public class ProductsOverviewList : System.Collections.Generic.List<Common.DomainClasses.ProductsOverviewObject> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ProductCategoryList", Namespace="http://schemas.datacontract.org/2004/07/Common.Dtos", ItemName="ProductCategory")]
    [System.SerializableAttribute()]
    public class ProductCategoryList : System.Collections.Generic.List<Common.DomainClasses.ProductCategory> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ProductSubcategoryList", Namespace="http://schemas.datacontract.org/2004/07/Common.Dtos", ItemName="ProductSubcategory")]
    [System.SerializableAttribute()]
    public class ProductSubcategoryList : System.Collections.Generic.List<Common.DomainClasses.ProductSubcategory> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductsService.IProductsService")]
    public interface IProductsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetProductsOverviewBy", ReplyAction="http://tempuri.org/IProductsService/GetProductsOverviewByResponse")]
        Demo.ServiceClients.Products.ProductsService.ProductsOverviewList GetProductsOverviewBy(System.Nullable<int> productCategoryID, System.Nullable<int> productSubcategoryID, string productNameString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetProductsOverviewBy", ReplyAction="http://tempuri.org/IProductsService/GetProductsOverviewByResponse")]
        System.Threading.Tasks.Task<Demo.ServiceClients.Products.ProductsService.ProductsOverviewList> GetProductsOverviewByAsync(System.Nullable<int> productCategoryID, System.Nullable<int> productSubcategoryID, string productNameString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetProductDetails", ReplyAction="http://tempuri.org/IProductsService/GetProductDetailsResponse")]
        Common.DomainClasses.Product GetProductDetails(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetProductDetails", ReplyAction="http://tempuri.org/IProductsService/GetProductDetailsResponse")]
        System.Threading.Tasks.Task<Common.DomainClasses.Product> GetProductDetailsAsync(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetProductCategories", ReplyAction="http://tempuri.org/IProductsService/GetProductCategoriesResponse")]
        Demo.ServiceClients.Products.ProductsService.ProductCategoryList GetProductCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetProductCategories", ReplyAction="http://tempuri.org/IProductsService/GetProductCategoriesResponse")]
        System.Threading.Tasks.Task<Demo.ServiceClients.Products.ProductsService.ProductCategoryList> GetProductCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetProductSubcategories", ReplyAction="http://tempuri.org/IProductsService/GetProductSubcategoriesResponse")]
        Demo.ServiceClients.Products.ProductsService.ProductSubcategoryList GetProductSubcategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetProductSubcategories", ReplyAction="http://tempuri.org/IProductsService/GetProductSubcategoriesResponse")]
        System.Threading.Tasks.Task<Demo.ServiceClients.Products.ProductsService.ProductSubcategoryList> GetProductSubcategoriesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductsServiceChannel : Demo.ServiceClients.Products.ProductsService.IProductsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductsServiceClient : System.ServiceModel.ClientBase<Demo.ServiceClients.Products.ProductsService.IProductsService>, Demo.ServiceClients.Products.ProductsService.IProductsService {
        
        public ProductsServiceClient() {
        }
        
        public ProductsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Demo.ServiceClients.Products.ProductsService.ProductsOverviewList GetProductsOverviewBy(System.Nullable<int> productCategoryID, System.Nullable<int> productSubcategoryID, string productNameString) {
            return base.Channel.GetProductsOverviewBy(productCategoryID, productSubcategoryID, productNameString);
        }
        
        public System.Threading.Tasks.Task<Demo.ServiceClients.Products.ProductsService.ProductsOverviewList> GetProductsOverviewByAsync(System.Nullable<int> productCategoryID, System.Nullable<int> productSubcategoryID, string productNameString) {
            return base.Channel.GetProductsOverviewByAsync(productCategoryID, productSubcategoryID, productNameString);
        }
        
        public Common.DomainClasses.Product GetProductDetails(int productId) {
            return base.Channel.GetProductDetails(productId);
        }
        
        public System.Threading.Tasks.Task<Common.DomainClasses.Product> GetProductDetailsAsync(int productId) {
            return base.Channel.GetProductDetailsAsync(productId);
        }
        
        public Demo.ServiceClients.Products.ProductsService.ProductCategoryList GetProductCategories() {
            return base.Channel.GetProductCategories();
        }
        
        public System.Threading.Tasks.Task<Demo.ServiceClients.Products.ProductsService.ProductCategoryList> GetProductCategoriesAsync() {
            return base.Channel.GetProductCategoriesAsync();
        }
        
        public Demo.ServiceClients.Products.ProductsService.ProductSubcategoryList GetProductSubcategories() {
            return base.Channel.GetProductSubcategories();
        }
        
        public System.Threading.Tasks.Task<Demo.ServiceClients.Products.ProductsService.ProductSubcategoryList> GetProductSubcategoriesAsync() {
            return base.Channel.GetProductSubcategoriesAsync();
        }
    }
}
