//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCS.WpfShop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RCS.WpfShop.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use shift-enter to break lines..
        /// </summary>
        public static string aaa {
            get {
                return ResourceManager.GetString("aaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application will close..
        /// </summary>
        public static string Closing {
            get {
                return ResourceManager.GetString("Closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour.
        /// </summary>
        public static string Colour {
            get {
                return ResourceManager.GetString("Colour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategory.
        /// </summary>
        public static string DetailFilter {
            get {
                return ResourceManager.GetString("DetailFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by: .
        /// </summary>
        public static string DeveloperLabel {
            get {
                return ResourceManager.GetString("DeveloperLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCS.
        /// </summary>
        public static string DeveloperLinkText {
            get {
                return ResourceManager.GetString("DeveloperLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/a-einstein.
        /// </summary>
        public static string DeveloperLinkUri {
            get {
                return ResourceManager.GetString("DeveloperLinkUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation: .
        /// </summary>
        public static string DocumentationLabel {
            get {
                return ResourceManager.GetString("DocumentationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WpfShop.
        /// </summary>
        public static string DocumentationLinkText {
            get {
                return ResourceManager.GetString("DocumentationLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/a-einstein/WpfShop/blob/master/README.md.
        /// </summary>
        public static string DocumentationLinkUri {
            get {
                return ResourceManager.GetString("DocumentationLinkUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Details.
        /// </summary>
        public static string ErrorDetails {
            get {
                return ResourceManager.GetString("ErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want the see the details?.
        /// </summary>
        public static string ErrorDetailsWanted {
            get {
                return ResourceManager.GetString("ErrorDetailsWanted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem using our data service.
        ///
        ///Please use the refresh button, or try again later..
        /// </summary>
        public static string ErrorService {
            get {
                return ResourceManager.GetString("ErrorService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an unknown problem.
        ///
        ///Do you want the see the details?.
        /// </summary>
        public static string ErrorUnknown {
            get {
                return ResourceManager.GetString("ErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop +.
        /// </summary>
        public static string IncreaseProduct {
            get {
                return ResourceManager.GetString("IncreaseProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        public static string Initializing {
            get {
                return ResourceManager.GetString("Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string MasterFilter {
            get {
                return ResourceManager.GetString("MasterFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string NavigateAbout {
            get {
                return ResourceManager.GetString("NavigateAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string NavigateShop {
            get {
                return ResourceManager.GetString("NavigateShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing found.
        ///Please try a different query..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CyclOne.
        /// </summary>
        public static string ShopName {
            get {
                return ResourceManager.GetString("ShopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name or Colour.
        /// </summary>
        public static string TextFilter {
            get {
                return ResourceManager.GetString("TextFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total value.
        /// </summary>
        public static string TotalValue {
            get {
                return ResourceManager.GetString("TotalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available.
        ///Would you like to update the application now?.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check for update..
        /// </summary>
        public static string UpdateCheckFailed {
            get {
                return ResourceManager.GetString("UpdateCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can continue using this version..
        /// </summary>
        public static string UpdateContinueCurrent {
            get {
                return ResourceManager.GetString("UpdateContinueCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be lead to the support page,
        ///where you can find installation instructions..
        /// </summary>
        public static string UpdateInstructions {
            get {
                return ResourceManager.GetString("UpdateInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough information to finish the update..
        /// </summary>
        public static string UpdateNoInformation {
            get {
                return ResourceManager.GetString("UpdateNoInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating.
        /// </summary>
        public static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        public static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
